Repository redBorder/cookbook-druid, pull requests merged in 2024-07, with the labels that each got.

#38 Feature/#17820 add intrusion pipeline
  resources/libraries/realtime.rb
Labels: kind/feature, size/S

#39 Release 1.5.0
  CHANGELOG.md
  resources/libraries/realtime.rb
  resources/metadata.rb
Labels: size/M, kind/feature

#41 Feature/incident response
  resources/libraries/realtime.rb
Labels: kind/feature, size/XS
