Repository redBorder/cookbook-druid, pull requests merged in 2024-06, with the labels that each got.

#34 Improvement/fix lint
  resources/attributes/default.rb
  resources/libraries/broker.rb
  resources/libraries/helper.rb
  resources/libraries/historical.rb
  resources/libraries/realtime.rb
  resources/providers/broker.rb
  resources/providers/common.rb
  resources/providers/coordinator.rb
  resources/providers/historical.rb
  resources/providers/middlemanager.rb
  resources/providers/overlord.rb
  resources/providers/realtime.rb
  resources/recipes/default.rb
  resources/resources/broker.rb
  resources/resources/common.rb
  resources/resources/coordinator.rb
  resources/resources/historical.rb
  resources/resources/middlemanager.rb
  resources/resources/overlord.rb
  resources/resources/realtime.rb
Labels: enhancement, kind/bug, lint, refactor

#35 Release 1.4.11
  .github/workflows/rpm.yml
  CHANGELOG.md
  README.md
  resources/attributes/default.rb
  resources/libraries/broker.rb
  resources/libraries/helper.rb
  resources/libraries/historical.rb
  resources/libraries/realtime.rb
  resources/metadata.rb
  resources/providers/broker.rb
  resources/providers/common.rb
  resources/providers/coordinator.rb
  resources/providers/historical.rb
  resources/providers/middlemanager.rb
  resources/providers/overlord.rb
  resources/providers/realtime.rb
  resources/recipes/default.rb
  resources/resources/broker.rb
  resources/resources/common.rb
  resources/resources/coordinator.rb
  resources/resources/historical.rb
  resources/resources/middlemanager.rb
  resources/resources/overlord.rb
  resources/resources/realtime.rb
Labels: kind/documentation

#36 Configure druid service log rotation
  resources/templates/default/log4j2.xml.erb
Labels: kind/feature, size/S
